# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAGJw-khFvYiImBLHihiHh2G1NQqaiyT
"""

!pip -q install flask transformers torch sentencepiece

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

MODEL_NAME = "google/flan-t5-large"  # ✅ much stronger than small/base

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

print("Loaded:", MODEL_NAME)

def generate_text(prompt, max_new_tokens=220):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)

    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        num_beams=4,              # ✅ better structure
        do_sample=False,          # ✅ deterministic
        early_stopping=True,
        repetition_penalty=1.2    # ✅ reduces repeating words
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)


def self_improve(user_prompt: str):
    user_prompt = (user_prompt or "").strip()
    if not user_prompt:
        return "", "", ""

    initial_prompt = f"""
Answer the user's question clearly and include a simple real-world example.
User question: {user_prompt}
"""
    initial = generate_text(initial_prompt, max_new_tokens=240)

    critique_prompt = f"""
You are an evaluator. Critique the answer below on:
1) clarity
2) correctness
3) completeness

Answer:
{initial}

Return 3 short bullet points.
"""
    critique = generate_text(critique_prompt, max_new_tokens=160)

    improve_prompt = f"""
Rewrite the answer using the critique. Make it:
- clearer
- more complete
- include a real-world example

Critique:
{critique}

Original answer:
{initial}

Improved answer:
"""
    improved = generate_text(improve_prompt, max_new_tokens=280)

    return initial, critique, improved

from flask import Flask, request, render_template_string
import threading

app = Flask(__name__)

HTML = r"""
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>DilipGPT</title>
  <style>
    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background-color: #0f172a;
      color: white;
    }

    .topbar {
      text-align: center;
      padding: 18px;
      font-size: 30px;
      font-weight: 800;
      background: #111827;
      border-bottom: 1px solid #1f2937;
      letter-spacing: 1px;
    }

    .container {
      max-width: 920px;
      margin: auto;
      padding: 22px;
    }

    textarea {
      width: 100%;
      padding: 14px;
      border-radius: 12px;
      border: 1px solid #374151;
      resize: none;
      font-size: 15px;
      background: #0b1220;
      color: white;
      outline: none;
    }

    textarea:focus {
      border-color: #14b8a6;
      box-shadow: 0 0 0 4px rgba(20,184,166,0.15);
    }

    button {
      margin-top: 12px;
      padding: 10px 22px;
      background-color: #14b8a6;
      border: none;
      border-radius: 12px;
      color: white;
      font-weight: 800;
      cursor: pointer;
      font-size: 14px;
    }

    button:hover {
      background-color: #0d9488;
    }

    .bubble {
      padding: 16px;
      border-radius: 14px;
      margin-top: 16px;
      line-height: 1.6;
      border: 1px solid rgba(255,255,255,0.08);
    }

    .user {
      background-color: rgba(59,130,246,0.12);
    }

    .assistant {
      background-color: rgba(20,184,166,0.10);
    }

    .title {
      font-weight: 900;
      margin-bottom: 8px;
      font-size: 16px;
    }

    pre {
      margin: 0;
      white-space: pre-wrap;
      word-break: break-word;
      font-family: Arial, sans-serif;
      font-size: 15px;
    }

    .grid {
      display: grid;
      grid-template-columns: 1fr;
      gap: 14px;
      margin-top: 10px;
    }

    @media (min-width: 900px){
      .grid { grid-template-columns: 1fr 1fr; }
    }
  </style>
</head>

<body>
  <div class="topbar">DilipGPT</div>

  <div class="container">
    <form method="post">
      <textarea name="prompt" rows="3" placeholder="Ask anything... (e.g., Explain reinforcement learning with an example)">{{prompt or ""}}</textarea>
      <br>
      <button type="submit">Send</button>
    </form>

    {% if prompt %}
      <div class="bubble user">
        <div class="title">You</div>
        <pre>{{prompt}}</pre>
      </div>
    {% endif %}

    {% if improved %}
      <div class="grid">
        <div class="bubble assistant">
          <div class="title">Initial Answer</div>
          <pre>{{initial}}</pre>
        </div>

        <div class="bubble assistant">
          <div class="title">Critique</div>
          <pre>{{critique}}</pre>
        </div>
      </div>

      <div class="bubble assistant">
        <div class="title">Improved Answer</div>
        <pre>{{improved}}</pre>
      </div>
    {% endif %}
  </div>
</body>
</html>
"""

@app.route("/", methods=["GET", "POST"])
def index():
    prompt = ""
    initial = critique = improved = ""

    if request.method == "POST":
        prompt = request.form.get("prompt", "").strip()
        if prompt:
            initial, critique, improved = self_improve(prompt)

    return render_template_string(
        HTML,
        prompt=prompt,
        initial=initial,
        critique=critique,
        improved=improved
    )

def run_app():
    app.run(host="0.0.0.0", port=5000, debug=False, use_reloader=False)

threading.Thread(target=run_app, daemon=True).start()
print("✅ DilipGPT running on port 5000")

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
print("cloudflared downloaded")

!rm -f cloudflared
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
!ls -l cloudflared

import subprocess, re, time

p = subprocess.Popen(
    ["./cloudflared", "tunnel", "--url", "http://localhost:5000"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

public_url = None
start = time.time()

while time.time() - start < 60 and public_url is None:
    line = p.stdout.readline()
    if not line:
        continue
    match = re.search(r"https://[a-zA-Z0-9\-]+\.trycloudflare\.com", line)
    if match:
        public_url = match.group(0)

print("✅ Public URL:", public_url if public_url else "❌ Not found. Scroll output above.")